include(`capitalize.m4')
define(`XC',`const [$1`Change$, set'_capitalize($1)`] = createSignal(), [use'_capitalize($1)`, '$1`$] = bind('$1`Change$, '$2)')
define(`RUS',`const [$1`, set'_capitalize($1)] = useState($2)')
define(`RUX',`const $1` = use'_capitalize($1)()')
define(`RR',`return (<div>$1</div>)')
define(`RC',`<$1 $2>$3</$1>')
define(`PC',`className="$1"')
define(`PO',`on$1={($2)=>$3}')
define(`POC',PO(Click,$1,$2))
